server:
  port: 0

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
  endpoint:
    health:
      show-details: always

feign:
  sentinel:
    enabled: true

logging:
  level:
    root: INFO
